// <auto-generated />
using System;
using EXAMPLE.Model.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EXAMPLE.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20230515133309_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EXAMPLE.Model.Books", b =>
                {
                    b.Property<int>("ID_BOOK")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_BOOK"));

                    b.Property<string>("AUTHOR")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("COST")
                        .HasColumnType("real");

                    b.Property<DateTime>("DATE_PUBLICATION")
                        .HasColumnType("datetime2");

                    b.Property<string>("DESCRIPTION")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GENRE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IMAGE_BOOK")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PATH_DOWNLOAD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("POPULARITY")
                        .HasColumnType("int");

                    b.Property<string>("TYPE_PRICE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_BOOK");

                    b.ToTable("BOOKS");
                });

            modelBuilder.Entity("EXAMPLE.Model.Busket", b =>
                {
                    b.Property<int>("ID_BUSKET")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_BUSKET"));

                    b.Property<int>("ID_USER")
                        .HasColumnType("int");

                    b.HasKey("ID_BUSKET");

                    b.ToTable("BUSKET");
                });

            modelBuilder.Entity("EXAMPLE.Model.BusketBooks", b =>
                {
                    b.Property<int>("ID_RECORD")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_RECORD"));

                    b.Property<int>("ID_BOOK")
                        .HasColumnType("int");

                    b.Property<int>("ID_BUSKET")
                        .HasColumnType("int");

                    b.HasKey("ID_RECORD");

                    b.ToTable("BUSKET_BOOKS");
                });

            modelBuilder.Entity("EXAMPLE.Model.Payment", b =>
                {
                    b.Property<int>("ID_PAY")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_PAY"));

                    b.Property<string>("DATE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ID_BOOK")
                        .HasColumnType("int");

                    b.Property<int>("ID_USER")
                        .HasColumnType("int");

                    b.Property<string>("NAME_OWNER")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NUMBER_CARD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("STATE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_PAY");

                    b.ToTable("PAYMENT");
                });

            modelBuilder.Entity("EXAMPLE.Model.ReviewProblem", b =>
                {
                    b.Property<int>("ID_REVIEW")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_REVIEW"));

                    b.Property<DateTime>("DATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("LOGIN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("REVIEW_TEXT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_REVIEW");

                    b.ToTable("REVIEW_PROBLEM");
                });

            modelBuilder.Entity("EXAMPLE.Model.Reviews", b =>
                {
                    b.Property<int>("ID_REVIEW")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_REVIEW"));

                    b.Property<DateTime>("DATE")
                        .HasColumnType("datetime2");

                    b.Property<int>("ID_BOOK")
                        .HasColumnType("int");

                    b.Property<string>("LOGIN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("REVIEW_TEXT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_REVIEW");

                    b.ToTable("REVIEWS");
                });

            modelBuilder.Entity("EXAMPLE.Model.User", b =>
                {
                    b.Property<int>("ID_USER")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_USER"));

                    b.Property<DateTime>("DATE_REGISTRATION")
                        .HasColumnType("datetime2");

                    b.Property<string>("EMAIL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IMAGE_PROFILE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LOGIN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PASSWORD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PHONE_NUMBER")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ROLE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_USER");

                    b.ToTable("USERS");
                });
#pragma warning restore 612, 618
        }
    }
}
